import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SessionWrapper from "@/components/auth/session-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body
          className={cn(
            "centered h-dvh w-full flex-col overflow-visible",
            inter.className,
          )}
        >
          <div className="centered h-dvh max-h-[1000px] w-full max-w-[425px] flex-col rounded-lg border-2">
            {children}
          </div>
        </body>
      </html>
    </SessionWrapper>
  );
}
